package no.ngu.geojson;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.JsonSerializer;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.jsontype.TypeSerializer;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.function.BiConsumer;
import java.util.stream.Stream;
import no.ngu.geojson.Geojson.Crs;

// https://en.wikipedia.org/wiki/GeoJSON

/**
 * Interface for all variants of geometry classes.
 * Each specific geometry class serializes and deserializes correctly with Jackson, and
 * has correct openapi descriptions generated by smallrye's openapi maven plugin.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
@JsonSubTypes({
  @JsonSubTypes.Type(value = Geometry.Point.class, name = "Point"),
  @JsonSubTypes.Type(value = Geometry.MultiPoint.class, name = "MultiPoint"),
  @JsonSubTypes.Type(value = Geometry.LineString.class, name = "LineString"),
  @JsonSubTypes.Type(value = Geometry.MultiLineString.class, name = "MultiLineString"),
  @JsonSubTypes.Type(value = Geometry.Polygon.class, name = "Polygon"),
  @JsonSubTypes.Type(value = Geometry.MultiPolygon.class, name = "MultiPolygon"),
  @JsonSubTypes.Type(value = Geometry.GeometryCollection.class, name = "GeometryCollection")
})
public sealed interface Geometry {

  private static <G extends Geometry> void writeGeometry(G geom, String type, String field,
      JsonGenerator generator, BiConsumer<G, JsonGenerator> rest) {
    try {
      generator.writeStartObject();
      generator.writeStringField("type", type);
      if (geom.crs() != null) {
        generator.writeFieldName("crs");
        generator.writeStartObject();
        generator.writeStringField("type", geom.crs().type());
        generator.writeFieldName("properties");
        generator.writeStartObject();
        for (var entry : geom.crs().properties().entrySet()) {
          generator.writeStringField(entry.getKey(), entry.getValue());
        }
        generator.writeEndObject();
        generator.writeEndObject();
      }
      generator.writeFieldName(field);
      rest.accept(geom, generator);
      generator.writeEndObject();
    } catch (IOException exception) {
      throw new RuntimeException("Failed to write geometry", exception);
    }
  }

  /**
   * Gets the coordinate reference system of this geometry, if any.
   *
   * @return the coordinate reference system, or null if not present
   */
  public Crs crs();

  /**
   * List of coordinates, at least x, y, but may also contain a z coordinate.
   * Should serialize as JSON array of numbers. 
   */
  public record Coordinates(List<Double> coordinates) implements Iterable<Double> {

    /**
     * Canonical constructor.
     */
    public Coordinates {
      if (coordinates.isEmpty()) {
        throw new IllegalArgumentException("List of coordinates cannot be empty");
      }
    }

    /**
     * Initialize with specific coordinates.
     *
     * @param x x coordinate
     * @param y y coordinate
     * @param z x coordinate
     */
    public Coordinates(double x, double y, double z) {
      this(Double.isNaN(z) ? List.of(x, y) : List.of(x, y, z));
    }
    
    /**
     * Initialize with specific coordinates.
     *
     * @param x x coordinate
     * @param y y coordinate
     */
    public Coordinates(double x, double y) {
      this(List.of(x, y));
    }

    private double coord(int pos) {
      return coordinates.size() > pos ? coordinates.get(pos) : Double.NaN;
    }

    /**
     * Gets the x coordinate.
     *
     * @return the x coordinate, NaN if not present
     */
    @SuppressWarnings("checkstyle:MethodName")
    public double x() {
      return coord(0);
    }
    
    /**
     * Gets the y coordinate.
     *
     * @return the y coordinate, NaN if not present
     */
    @SuppressWarnings("checkstyle:MethodName")
    public double y() {
      return coord(1);
    }
    
    /**
     * Gets the z coordinate.
     *
     * @return the z coordinate, NaN if not present
     */
    @SuppressWarnings("checkstyle:MethodName")
    public double z() {
      return coord(2);
    }

    @Override
    public Iterator<Double> iterator() {
      return coordinates.iterator();
    }

    private static Coordinates geoJson(List<Double> coords) {
      return new Coordinates(coords);
    }

    private void serialize(JsonGenerator generator) {
      try {
        generator.writeStartArray();
        for (var coord : coordinates) {
          generator.writeNumber(coord);
        }
        generator.writeEndArray();
      } catch (IOException exception) {
        throw new RuntimeException("Failed to write coordinates", exception);
      }
    }
  }

  /**
   * GeoJSON Point class.
   */
  // {
  //   "type": "Point", 
  //   "coordinates": [30.0, 10.0]
  // }
  @JsonSerialize(using = Point.GeojsonSerializer.class)
  public record Point(Crs crs, Coordinates coordinates) implements Geometry {
    /**
     * Initialize with specific coordinates.
     *
     * @param coordinates coordinates
     */
    public Point(Coordinates coordinates) {
      this(null, coordinates);
    }

    /**
     * Initialize with crs and specific coordinates.
     *
     * @param x x coordinate
     * @param y y coordinate
     * @param z x coordinate
     */
    public Point(Crs crs, double x, double y, double z) {
      this(crs, new Coordinates(x, y, z));
    }

    /**
     * Initialize with specific coordinates.
     *
     * @param x x coordinate
     * @param y y coordinate
     * @param z x coordinate
     */
    public Point(double x, double y, double z) {
      this(null, x, y, z);
    }
  
    /**
     * Initialize with crs and specific coordinates.
     *
     * @param crs the coordinate reference system
     * @param x x coordinate
     * @param y y coordinate
     */
    public Point(Crs crs, double x, double y) {
      this(crs, new Coordinates(x, y));
    }
  
    /**
     * Initialize with specific coordinates.
     *
     * @param x x coordinate
     * @param y y coordinate
     */
    public Point(double x, double y) {
      this(null, x, y);
    }
  
    /**
     * Gets the x coordinate.
     *
     * @return the x coordinate, NaN if not present
     */
    @SuppressWarnings("checkstyle:MethodName")
    public double x() {
      return coordinates.coord(0);
    }
  
    /**
     * Gets the y coordinate.
     *
     * @return the y coordinate, NaN if not present
     */
    @SuppressWarnings("checkstyle:MethodName")
    public double y() {
      return coordinates.coord(1);
    }
  
    /**
     * Gets the z coordinate.
     *
     * @return the z coordinate, NaN if not present
     */
    @SuppressWarnings("checkstyle:MethodName")
    public double z() {
      return coordinates.coord(2);
    }

    /**
     * Jackson deserializer method for Point.
     *
     * @param coords the coordinates
     * @return the new Point
     */
    @JsonCreator
    public static Point geoJson(
        @JsonProperty("crs") Crs crs,
        @JsonProperty(value = "coordinates", required = true) List<Double> coords
    ) {
      return new Point(crs, Coordinates.geoJson(coords));
    }

    /**
     * Jackson serializer class for Point.
     */
    public static class GeojsonSerializer extends JsonSerializer<Point> {
  
      @Override
      public void serialize(Point point, JsonGenerator generator, SerializerProvider serializers) {
        Geometry.writeGeometry(point, "Point", "coordinates", generator,
            (geom, gen) -> geom.coordinates().serialize(gen)
        );
      }

      @Override
      public void serializeWithType(Point point, JsonGenerator generator,
          SerializerProvider serializers, TypeSerializer typeSerializer) throws IOException {
        serialize(point, generator, serializers);
      }
    }
  }
  
  /**
   * List of list of coordinates.
   */
  public record CoordinatesList(List<Coordinates> coordinates) implements Iterable<Coordinates> {

    /**
     * Canonical constructor.
     */
    public CoordinatesList {
      if (coordinates.size() == 0) {
        throw new IllegalArgumentException("List of coordinates cannot be empty");
      }
    }

    /**
     * Initializes with specific Points.
     *
     * @param points the points
     */
    public CoordinatesList(Point... points) {
      this(Stream.of(points).map(Point::coordinates).toList());
    }

    @Override
    public Iterator<Coordinates> iterator() {
      return coordinates.iterator();
    }

    /**
     * The list as a list of Points.
     *
     * @return a list of Points
     */
    public List<Point> points() {
      return coordinates.stream().map(coords -> new Point(null, coords)).toList();
    }

    private static CoordinatesList geoJson(List<List<Double>> coords) {
      return new CoordinatesList(coords.stream().map(Coordinates::geoJson).toList());
    }

    private void serialize(JsonGenerator generator) {
      try {
        generator.writeStartArray();
        for (var coords : coordinates) {
          coords.serialize(generator);
        }
        generator.writeEndArray();
      } catch (IOException exception) {
        throw new RuntimeException("Failed to write coordinates list", exception);
      }
    }
  }

  /**
   * GeoJSON MultiPoint class.
   */
  // {
  //   "type": "MultiPoint", 
  //   "coordinates": [
  //       [10.0, 40.0],
  //       [40.0, 30.0],
  //       [20.0, 20.0],
  //       [30.0, 10.0]
  //   ]
  // }
  @JsonSerialize(using = MultiPoint.GeojsonSerializer.class)
  public record MultiPoint(Crs crs, CoordinatesList coordinates) implements Geometry,
      Iterable<Point> {

    /**
     * Initialize with crs and Point objects.
     *
     * @param crs the coordinate reference system
     * @param points the points
     */
    public MultiPoint(Crs crs, Point... points) {
      this(crs, new CoordinatesList(points));
    }

    /**
     * Initialize with coordinates list.
     *
     * @param coordinates coordinates
     */
    public MultiPoint(CoordinatesList coordinates) {
      this(null, coordinates);
    }

    /**
     * Initialize with Point objects.
     *
     * @param points the points
     */
    public MultiPoint(Point... points) {
      this(null, points);
    }

    @Override
    public Iterator<Point> iterator() {
      return coordinates().points().iterator();
    }

    /**
     * Get the points making up this MultiPoint.
     *
     * @return the points
     */
    public List<Point> points() {
      return coordinates().points();
    }

    /**
     * Jackson deserializer method for MultiPoint.
     *
     * @param coords the coordinates
     * @return the new MultiPoint
     */
    @JsonCreator
    public static MultiPoint geoJson(
        @JsonProperty("crs") Crs crs,
        @JsonProperty(value = "coordinates", required = true) List<List<Double>> coords
    ) {
      return new MultiPoint(crs, CoordinatesList.geoJson(coords));
    }

    /**
     * Jackson serializer class for MultiPoint.
     */
    public static class GeojsonSerializer extends JsonSerializer<MultiPoint> {
  
      @Override
      public void serialize(
          MultiPoint multiPoint,
          JsonGenerator generator,
          SerializerProvider serializers
      ) {
        Geometry.writeGeometry(
            multiPoint,
            "MultiPoint",
            "coordinates",
            generator,
            (geom, gen) -> geom.coordinates.serialize(gen)
        );
      }

      @Override
      public void serializeWithType(MultiPoint multiPoint, JsonGenerator generator,
          SerializerProvider serializers, TypeSerializer typeSerializer) throws IOException {
        serialize(multiPoint, generator, serializers);
      }
    }
  }
  
  /**
   * GeoJSON LineString class.
   */
  // {
  //   "type": "LineString", 
  //   "coordinates": [
  //       [30.0, 10.0],
  //       [10.0, 30.0],
  //       [40.0, 40.0]
  //   ]
  // }
  @JsonSerialize(using = LineString.GeojsonSerializer.class)
  public record LineString(Crs crs, CoordinatesList coordinates) implements Geometry,
      Iterable<Point> {

    /**
     * Initialize with coordinates list.
     *
     * @param coordinates coordinates
     */
    public LineString(CoordinatesList coordinates) {
      this(null, coordinates);
    }

    /**
     * Initialize with crs and Point objects.
     *
     * @param crs the coordinate reference system
     * @param points the points
     */
    public LineString(Crs crs, Point... points) {
      this(crs, new CoordinatesList(points));
    }

    /**
     * Initialize with Point objects.
     *
     * @param points the points
     */
    public LineString(Point... points) {
      this(null, points);
    }
  
    @Override
    public Iterator<Point> iterator() {
      return coordinates().points().iterator();
    }

    /**
     * Jackson deserializer method for LineString.
     *
     * @param coords the coordinates
     * @return the new LineString
     */
    @JsonCreator
    public static LineString geoJson(
        @JsonProperty("crs") Crs crs,
        @JsonProperty(value = "coordinates", required = true) List<List<Double>> coords
    ) {
      return new LineString(crs, CoordinatesList.geoJson(coords));
    }

    /**
     * Jackson serializer class for LineString.
     */
    public static class GeojsonSerializer extends JsonSerializer<LineString> {
  
      @Override
      public void serialize(LineString lineString, JsonGenerator generator,
          SerializerProvider serializers) {
        Geometry.writeGeometry(lineString, "LineString", "coordinates", generator,
            (geom, gen) -> geom.coordinates.serialize(gen));
      }

      @Override
      public void serializeWithType(LineString lineString, JsonGenerator generator,
          SerializerProvider serializers, TypeSerializer typeSerializer) throws IOException {
        serialize(lineString, generator, serializers);
      }
    }
  }

  /**
   * List of list of coordinates.
   */
  public record CoordinatesLists(List<CoordinatesList> coordinates)
      implements Iterable<CoordinatesList> {

    /**
     * Canonical constructor.
     */
    public CoordinatesLists {
      if (coordinates.size() == 0) {
        throw new IllegalArgumentException("List of coordinates cannot be empty");
      }
    }

    /**
     * Initializes with CoordinatesLists.
     *
     * @param coordinates the coordinates
     */
    public CoordinatesLists(CoordinatesList... coordinates) {
      this(List.of(coordinates));
    }

    /**
     * Initializes with LineStrings.
     *
     * @param lines the lines
     */
    public CoordinatesLists(LineString... lines) {
      this(Stream.of(lines).map(LineString::coordinates).toList());
    }

    @Override
    public Iterator<CoordinatesList> iterator() {
      return coordinates.iterator();
    }

    /**
     * The coordinates as a list of MultiPoints.
     *
     * @return a list of MultiPoints
     */
    public List<MultiPoint> multiPoints() {
      return coordinates.stream().map(MultiPoint::new).toList();
    }

    /**
     * The coordinates as a list of LineStrings.
     *
     * @return a list of LineStrings
     */
    public List<LineString> lineStrings() {
      return coordinates.stream().map(LineString::new).toList();
    }

    private static CoordinatesLists geoJson(List<List<List<Double>>> coords) {
      return new CoordinatesLists(coords.stream().map(CoordinatesList::geoJson).toList());
    }

    private void serialize(JsonGenerator generator) {
      try {
        generator.writeStartArray();
        for (var coords : coordinates) {
          coords.serialize(generator);
        }
        generator.writeEndArray();
      } catch (IOException exception) {
        throw new RuntimeException("Failed to write coordinates lists", exception);
      }
    }
  }

  /**
   * GeoJSON MultiLineString class.
   */
  // {
  //   "type": "MultiLineString", 
  //   "coordinates": [
  //       [
  //           [10.0, 10.0],
  //           [20.0, 20.0],
  //           [10.0, 40.0]
  //       ],
  //       [
  //           [40.0, 40.0],
  //           [30.0, 30.0],
  //           [40.0, 20.0],
  //           [30.0, 10.0]
  //       ]
  //   ]
  // }
  @JsonSerialize(using = MultiLineString.GeojsonSerializer.class)
  public record MultiLineString(Crs crs, CoordinatesLists coordinates)
      implements Geometry, Iterable<LineString> {

    /**
     * Initialize with coordinates lists.
     *
     * @param coordinates the coordinates
     */
    public MultiLineString(CoordinatesLists coordinates) {
      this(null, coordinates);
    }

    /**
     * Initialize with crs and a list of CoordinatesList.
     *
     * @param crs the coordinate reference system
     * @param coordinates the coordinates
     */
    public MultiLineString(Crs crs, List<CoordinatesList> coordinates) {
      this(crs, new CoordinatesLists(coordinates));
    }

    /**
     * Initialize with a list of CoordinatesList.
     *
     * @param coordinates the coordinates
     */
    public MultiLineString(List<CoordinatesList> coordinates) {
      this(null, coordinates);
    }

    /**
     * Initialize with crs and CoordinatesList objects.
     *
     * @param crs the coordinate reference system
     * @param coordinates the coordinates
     */
    public MultiLineString(Crs crs, CoordinatesList... coordinates) {
      this(crs, new CoordinatesLists(List.of(coordinates)));
    }

    /**
     * Initialize with CoordinatesList objects.
     *
     * @param coordinates the coordinates
     */
    public MultiLineString(CoordinatesList... coordinates) {
      this(null, coordinates);
    }

    /**
     * Initialize with crs and LineString objects.
     *
     * @param crs the coordinate reference system
     * @param lines the lines
     */
    public MultiLineString(Crs crs, LineString... lines) {
      this(crs, new CoordinatesLists(Stream.of(lines).map(LineString::coordinates).toList()));
    }

    /**
     * Initialize with LineString objects.
     *
     * @param lines the lines
     */
    public MultiLineString(LineString... lines) {
      this(null, lines);
    }

    @Override
    public Iterator<LineString> iterator() {
      return coordinates.lineStrings().iterator();
    }
  
    /**
     * The coordinates as a list of LineStrings.
     *
     * @return a list of LineStrings
     */
    public List<LineString> lineStrings() {
      return coordinates.lineStrings();
    }

    /**
     * Jackson deserializer method for MultiLineString.
     *
     * @param coords the coordinates
     * @return the new MultiLineString
     */
    @JsonCreator
    public static MultiLineString geoJson(
      @JsonProperty("crs") Crs crs,
      @JsonProperty(value = "coordinates", required = true) List<List<List<Double>>> coords
    ) {
      return new MultiLineString(crs, CoordinatesLists.geoJson(coords));
    }

    /**
     * Jackson serializer class for MultiLineString.
     */
    public static class GeojsonSerializer extends JsonSerializer<MultiLineString> {
  
      @Override
      public void serialize(MultiLineString multiLineString, JsonGenerator generator,
          SerializerProvider serializers) {
        Geometry.writeGeometry(multiLineString, "MultiLineString", "coordinates", generator,
            (geom, gen) -> geom.coordinates().serialize(gen));
      }

      @Override
      public void serializeWithType(MultiLineString multiLineString, JsonGenerator generator,
          SerializerProvider serializers, TypeSerializer typeSerializer) throws IOException {
        serialize(multiLineString, generator, serializers);
      }
    }
  }

  /**
   * GeoJSON Polygon class.
   */
  // {
  //   "type": "Polygon", 
  //   "coordinates": [
  //       [
  //           [35.0, 10.0],
  //           [45.0, 45.0],
  //           [15.0, 40.0],
  //           [10.0, 20.0],
  //           [35.0, 10.0]
  //       ],
  //       [
  //           [20.0, 30.0],
  //           [35.0, 35.0],
  //           [30.0, 20.0],
  //           [20.0, 30.0]
  //       ]
  //   ]
  // }
  @JsonSerialize(using = Polygon.GeojsonSerializer.class)
  public record Polygon(Crs crs, CoordinatesLists coordinates) implements Geometry {
  
    private static List<LineString> lines(LineString outline, List<LineString> holes) {
      var lines = new ArrayList<>(holes);
      lines.add(0, outline);
      return lines;
    }

    /**
     * Initialize with coordinates lists.
     *
     * @param coordinates the coordinates
     */
    public Polygon(CoordinatesLists coordinates) {
      this(null, coordinates);
    }

    /**
     * Initialize with crs, outline and holes.
     *
     * @param crs the coordinate reference system
     * @param outline the outline
     * @param holes the holes
     */
    public Polygon(Crs crs, LineString outline, List<LineString> holes) {
      this(
        crs,
        new CoordinatesLists(lines(outline, holes).stream()
          .map(LineString::coordinates)
          .toList()
      ));
    }

    /**
     * Initialize with outline and holes.
     *
     * @param outline the outline
     * @param holes the holes
     */
    public Polygon(LineString outline, List<LineString> holes) {
      this(null, outline, holes);
    }

    /**
     * Initialize with crs, outline and holes.
     *
     * @param crs the coordinate reference system
     * @param outline the outline
     * @param holes the holes
     */
    public Polygon(Crs crs, LineString outline, LineString... holes) {
      this(crs, outline, List.of(holes));
    }

    /**
     * Initialize with outline and holes.
     *
     * @param outline the outline
     * @param holes the holes
     */
    public Polygon(LineString outline, LineString... holes) {
      this(null, outline, holes);
    }

    /**
     * Gets the outline.
     *
     * @return the outline
     */
    public LineString outline() {
      var coords = coordinates.coordinates();
      return new LineString(crs, coords.get(0));
    }

    /**
     * Gets the holes.
     *
     * @return the holes
     */
    public List<LineString> holes() {
      var coords = coordinates.coordinates();
      return coords.subList(1, coords.size()).stream().map(c -> new LineString(crs, c)).toList();
    }

    /**
     * Jackson deserializer method for Polygon.
     *
     * @param coords the coordinates
     * @return the new Polygon
     */
    @JsonCreator
    public static Polygon geoJson(
        @JsonProperty("crs") Crs crs,
        @JsonProperty(value = "coordinates", required = true) List<List<List<Double>>> coords
    ) {
      var holes = coords.subList(1, coords.size()).stream()
          .map(c -> LineString.geoJson(null, c))
          .toList();
      return new Polygon(crs, LineString.geoJson(null, coords.get(0)), holes);
    }

    /**
     * Jackson serializer class for Polygon.
     */
    public static class GeojsonSerializer extends JsonSerializer<Polygon> {
  
      @Override
      public void serialize(Polygon polygon, JsonGenerator generator,
          SerializerProvider serializers) {
        Geometry.writeGeometry(polygon, "Polygon", "coordinates", generator,
            (geom, gen) -> geom.coordinates().serialize(gen));
      }

      @Override
      public void serializeWithType(Polygon polygon, JsonGenerator generator,
          SerializerProvider serializers, TypeSerializer typeSerializer) throws IOException {
        serialize(polygon, generator, serializers);
      }
    }
  }

  /**
   * GeoJSON MultiPolygon class.
   */
  // {
  //   "type": "MultiPolygon", 
  //   "coordinates": [
  //       [
  //           [
  //               [40.0, 40.0],
  //               [20.0, 45.0],
  //               [45.0, 30.0],
  //               [40.0, 40.0]
  //           ]
  //       ], 
  //       [
  //           [
  //               [20.0, 35.0],
  //               [10.0, 30.0],
  //               [10.0, 10.0],
  //               [30.0, 5.0],
  //               [45.0, 20.0],
  //               [20.0, 35.0]
  //           ],
  //           [
  //               [30.0, 20.0],
  //               [20.0, 15.0],
  //               [20.0, 25.0],
  //               [30.0, 20.0]
  //           ]
  //       ]
  //   ]
  // }
  @JsonSerialize(using = MultiPolygon.GeojsonSerializer.class)
  public record MultiPolygon(Crs crs, List<CoordinatesLists> coordinates) implements Geometry {

    /**
     * Initialize with coordinates lists.
     *
     * @param coordinates the coordinates
     */
    public MultiPolygon(List<CoordinatesLists> coordinates) {
      this(null, coordinates);
    }

    /**
     * Canonical constructor.
     */
    public MultiPolygon {
      if (coordinates.size() == 0) {
        throw new IllegalArgumentException("List of coordinates cannot be empty");
      }
    }

    /**
     * Initializes with Polygons.
     *
     * @param polygons the polygons
     */
    public MultiPolygon(Polygon... polygons) {
      this(null, polygons);
    }

    /**
     * Initializes with crs and Polygons.
     *
     * @param crs the coordinate reference system
     * @param polygons the polygons
     */
    public MultiPolygon(Crs crs, Polygon... polygons) {
      this(crs, Stream.of(polygons).map(Polygon::coordinates).toList());
    }
  
    /**
     * Jackson deserializer method for MultiPolygon.
     *
     * @param coords the coordinates
     * @return the new MultiPolygon
     */
    @JsonCreator
    public static MultiPolygon geoJson(
      @JsonProperty("crs") Crs crs,
      @JsonProperty(value = "coordinates", required = true)
      List<List<List<List<Double>>>> coords
    ) {
      return new MultiPolygon(crs, coords.stream().map(CoordinatesLists::geoJson).toList());
    }

    /**
     * Jackson serializer class for MultiPolygon.
     */
    public static class GeojsonSerializer extends JsonSerializer<MultiPolygon> {
  
      @Override
      public void serialize(MultiPolygon multiPolygon, JsonGenerator generator,
          SerializerProvider serializers) {
        Geometry.writeGeometry(
            multiPolygon,
            "MultiPolygon",
            "coordinates",
            generator,
            (geom, gen) -> {
              try {
                gen.writeStartArray();
                for (var coords : multiPolygon.coordinates) {
                  coords.serialize(gen);
                }
                gen.writeEndArray();
              } catch (IOException exception) {
                throw new RuntimeException("Failed to write multipolygon", exception);
              }
            }
        );
      }

      @Override
      public void serializeWithType(MultiPolygon multiPolygon, JsonGenerator generator,
          SerializerProvider serializers, TypeSerializer typeSerializer) throws IOException {
        serialize(multiPolygon, generator, serializers);
      }
    }
  }

  /**
   * GeoJSON GeometryCollection class.
   */
  // {
  //   "type": "GeometryCollection",
  //   "geometries": [
  //       {
  //           "type": "Point",
  //           "coordinates": [40.0, 10.0]
  //       },
  //       {
  //           "type": "LineString",
  //           "coordinates": [
  //               [10.0, 10.0],
  //               [20.0, 20.0],
  //               [10.0, 40.0]
  //           ]
  //       },
  //       {
  //           "type": "Polygon",
  //           "coordinates": [
  //               [
  //                   [40.0, 40.0],
  //                   [20.0, 45.0],
  //                   [45.0, 30.0],
  //                   [40.0, 40.0]
  //               ]
  //           ]
  //       }
  //   ]
  // }
  @JsonSerialize(using = GeometryCollection.GeojsonSerializer.class)
  public record GeometryCollection(Crs crs, List<Geometry> geometries) implements Geometry {

    /**
     * Initializes with geometry list.
     *
     * @param geometries the geometries
     */
    public GeometryCollection(List<Geometry> geometries) {
      this(null, geometries);
    }

    /**
     * Initializes with crs and Geometry objects.
     *
     * @param crs the coordinate reference system
     * @param items the geometry
     */
    public GeometryCollection(Crs crs, Geometry... items) {
      this(crs, List.of(items));
    }

    /**
     * Initializes with Geometry objects.
     *
     * @param items the geometry
     */
    public GeometryCollection(Geometry... items) {
      this(null, items);
    }

    /**
     * Jackson deserializer method for GeometryCollection.
     *
     * @param geometries the geometries
     * @return the new GeometryCollection
     */
    @JsonCreator
    public static GeometryCollection geoJson(
      @JsonProperty("crs") Crs crs,
      @JsonProperty(value = "geometries", required = true) List<Geometry> geometries
    ) {
      return new GeometryCollection(crs, geometries);
    }

    /**
     * Jackson serializer class for GeometryCollection.
     */
    public static class GeojsonSerializer extends JsonSerializer<GeometryCollection> {
  
      @Override
      public void serialize(GeometryCollection geometryCollection, JsonGenerator generator,
          SerializerProvider serializers) {
        Geometry.writeGeometry(geometryCollection, "GeometryCollection", "geometries", generator,
            (geom, gen) -> {
              try {
                gen.writeStartArray();
                for (var geometry : geom.geometries()) {
                  serializers.defaultSerializeValue(geometry, gen);
                }
                gen.writeEndArray();
              } catch (IOException exception) {
                throw new RuntimeException("Failed to write geometry collection", exception);
              }
            }
        );
      }

      @Override
      public void serializeWithType(GeometryCollection geometryCollection, JsonGenerator generator,
          SerializerProvider serializers, TypeSerializer typeSerializer) throws IOException {
        serialize(geometryCollection, generator, serializers);
      }
    }
  }
}
